#!/usr/bin/env ruby

load File.join(File.dirname(__FILE__), "../server/all.rb")

metric = Core::Metric.new(ARGV.shift || raise("Need metric name"))
number_seconds = (ARGV.shift || raise("Need total number of seconds")).to_i
rate = (ARGV.shift || raise("Need rate (# metrics / second)")).to_i

generator = Generator.new(metric)
now = Time.now.to_i
0.upto(number_seconds) do |num|
  val = generator.generate(:timestamp => Time.at(now - num))
  puts "%s,%s" % [val.timestamp_string, val.value]
end
