#!/usr/bin/env ruby

# Examples:
#   script/generate heartrate 60
#   script/generate ekg 10

load File.join(File.dirname(__FILE__), "../server/all.rb")

require 'net/http'

metric = Core::Metric.new(ARGV.shift || raise("Need metric name"))
rate = (ARGV.shift || raise("Need rate (# metrics / second)")).to_i

generator = Generator.new(metric)
data_server_uri = "http://localhost:11000/metrics/%s" % metric.name
uri = URI(data_server_uri)

sleep_time = 1.0/rate
while true
  value = generator.generate
  begin
    Net::HTTP.post_form(uri, 'timestamp' => value.timestamp_string, 'value' => value.value)
  rescue Exception => e
    puts "ERROR: %s" % e.to_s
  end
  sleep(sleep_time)
end
