#!/usr/bin/env ruby

# Example:
# script/subscriber heartrate "http://localhost:3000/mbryzek"

require 'net/http'

load File.join(File.dirname(__FILE__), "../server/all.rb")

metric = Core::Metric.new(ARGV.shift || raise("Need metric name"))
url = ARGV.shift || raise("Need url")

generator = Generator.new(metric)
uri = URI(url)

counter = 0
while true
  val = generator.generate
  begin
    Net::HTTP.post_form(uri, 'metric' => metric.name, 'timestamp' => val.timestamp_string, 'value' => val.value)
  rescue Exception => e
    puts "ERROR: %s" % e.to_s
  end

  counter += 1
  if counter % 10 == 0
    puts " - %s events published" % counter
  end

  sleep(rand(100) / 100.0)
end
